# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 03:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='menu',
        ),
        migrations.AlterField(
            model_name='article',
            name='files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_articles', to='article.File', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='file',
            name='create_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_files', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
    ]
