# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 03:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='目录名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用标记')),
                ('administrators', models.ManyToManyField(blank=True, related_name='managed_menus', to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_menus', to=settings.AUTH_USER_MODEL, verbose_name='拥有人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu', verbose_name='父项名称')),
            ],
            options={
                'verbose_name_plural': '目录列表',
                'verbose_name': '目录',
            },
        ),
    ]
