# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['create_time'], 'verbose_name': '目录', 'verbose_name_plural': '目录列表'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='enabled',
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='目录名称'),
        ),
    ]
