# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPickle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField(verbose_name='字符数据')),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
