# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20161029_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=50, verbose_name='目录名称'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([('parent', 'name')]),
        ),
    ]
